# Generated by Django 5.0.3 on 2025-02-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaccount',
            old_name='business_addresss',
            new_name='business_address',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='image',
        ),
    ]
