# Generated by Django 5.0.3 on 2025-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_business_addresss_businessaccount_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='1234567890', max_length=200, null=True),
        ),
    ]
