# Generated by Django 5.2 on 2025-04-15 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_twofactor_enabled', models.BooleanField(default=False)),
                ('twoFaCode', models.CharField(max_length=200)),
                ('twoFa_created', models.DateTimeField(blank=True, null=True)),
                ('twoFaBackUp', models.JSONField(blank=True, default=list)),
                ('is_email_enabled', models.BooleanField(default=False)),
                ('email_otp', models.CharField(blank=True, max_length=200, null=True)),
                ('email_created', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
